trigger: none 
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

extends:
  template: service.pipeline.stage.yml@self
  parameters:
    enviornmentPrefix: EventStore
    componentName: EventStore_Api

