parameters:
-name: platformEnviornmentPrefix
 type: string
-name: projectVariables
 type: object
-name: agentPoolName
displayName: Agent pool to use for the Build job
type: string 
default: ubunt-latest
variables: 
- template:${{ parameters.projectVariables.file}}@${{parameters.projectVariables.repository}}

stages:
- stage: Build
  jobs:
  -template: build/dotnet.build.jobs.yaml
   parameters:
    buildConfiguration: Release 
    agentPoolName: ${{parameters.agentPoolName}}
    publishArtifacts: ne(variables['Build.Reason'], 'PullRequest')
    postBuildSteps: ${{parameters.postBuildSteps}}

